Controllers/AdvController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Caching;
using System.Text;
using System.Web;
using System.Web.Caching;
using System.Web.Mvc;
using System.Xml;
using System.Xml.Serialization;
using BootStrap.Models;
using DAL;
using RmsAuto.TechDoc;
using RmsAuto.TechDoc.Entities.TecdocBase;
using WebMatrix.WebData;
using CacheItemPriority = System.Web.Caching.CacheItemPriority;

namespace AdvSpareAuto.Controllers
{
    [XmlRoot("auto-catalog")]
    public class auto_catalog
    {
        [XmlElement("creation-date")]
        public string creation_date;

        [XmlElement("host")]
        public string host;

        [XmlElement("offers")]
        public offers offers;

    }

    [XmlRoot("offers")]
    public class offers
    {
        
        [XmlElement("offer")]
        public List<CarAdvXmlFeed> offer { get; set; }
    }

    public class ParameterBinder : IModelBinder
    {
        public string ActualParameter { get; private set; }

        public ParameterBinder(string actualParameter)
        {
            this.ActualParameter = actualParameter;
        }

        public object BindModel(ControllerContext controllerContext, ModelBindingContext bindingContext)
        {
            object id = controllerContext.RouteData.Values[this.ActualParameter];
            return id;
        }
    }

    [AttributeUsage(AttributeTargets.Parameter)]
    public class BindParameterAttribute : CustomModelBinderAttribute
    {
        public string ActualParameter { get; private set; }

        public BindParameterAttribute(string actualParameter)
        {
            this.ActualParameter = actualParameter;
        }

        public override IModelBinder GetBinder()
        {
            return new ParameterBinder(this.ActualParameter);
        }
    }

    public class AdvController : Controller
    {

        private IAdvRepository _advRepository;
        private int pageSize = 12;
        private int _carCategory = 49;
        private int _maxPageCount = 15;

        public AdvController(IAdvRepository advRepository)
        {
            _advRepository = advRepository;
        }

        [HttpGet]
        public ActionResult PostAdv()
        {
            ViewBag.Message = "разместить объявление о продаже; подать объявление; Москва, Санкт-Петербург, Екатеринбург, Краснодар, Новосибирск";
            var model = _advRepository.Get(0);
            model.CurrentUser = _advRepository.GetUser(WebSecurity.CurrentUserId);
            if (model.CurrentUser == null)
                model.CurrentUser = new RegisterModel();
            return View(model);
        }

        public void SaveClickIP()
        {
            using (var ctx = new AdvContext())
            {
                ctx.Database.ExecuteSqlCommand("Insert into ClickIP (IP) values ('"+Request.UserHostAddress+"')");
                
            }
        }

        public ActionResult CarAdvTips()
        {
            ViewBag.Message = "разместить объявление о продаже; подать объявление; Москва, Санкт-Петербург, Екатеринбург, Краснодар, Новосибирск";
            

            return View();
        }



        public ActionResult PostResume()
        {
            ViewBag.Message = "разместить объявление о продаже; подать объявление; Москва, Санкт-Петербург, Екатеринбург, Краснодар, Новосибирск";
            var model = _advRepository.Get(0);
            model.CurrentUser = _advRepository.GetUser(WebSecurity.CurrentUserId);
            



            if (model.CurrentUser == null)
                model.CurrentUser = new RegisterModel();
            return View(model);
        }

        [HttpGet]
        public ActionResult PostCarAdv()
        {
            ViewBag.Message = "разместить объявление о продаже; подать объявление; Москва, Санкт-Петербург, Екатеринбург, Краснодар, Новосибирск";
            var model = _advRepository.Get(0);
            model.CurrentUser = _advRepository.GetUser(WebSecurity.CurrentUserId);
            

            if (model.CurrentUser == null)
                model.CurrentUser = new RegisterModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult PostAdv(AdvModel model)
        {
            return RedirectToAction("CreateAdv");
        }

        public ActionResult Help(AdvModel model)
        {
            return View();
        }

        public ActionResult Delete(int Id)
        {
            var model = _advRepository.Get(Id);
            if (model.SellerId == WebSecurity.CurrentUserId)
            {
                _advRepository.Delete(Id);
                return View("Delete");
            }
            else
            {
                return View("Error");
            }
        }

        public ActionResult Edit(int Id)
        {
            var model = _advRepository.Get(Id);
            model.CurrentUser = _advRepository.GetUser(WebSecurity.CurrentUserId);
            if (model.SellerId == WebSecurity.CurrentUserId)
            {
                return View(model);
            }
            else
            {
                return View("Error");
            }
        }


        [HttpPost]
        public ActionResult CreateAdv(CarAdvModel model)
        {
            if (model.Category == 0) return View("Error", new ErrorInfo() { message = "Заполните категорию" });

            foreach (var fileKey in Request.Files.AllKeys)
            {
                var file = Request.Files[fileKey];
                try
                {
                    if (file != null && file.InputStream.Length > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        var b = new byte[file.InputStream.Length];
                        file.InputStream.Read(b, 0, (int)file.InputStream.Length);

                        model.Imgs.Add(new ImageFile() { FileBody = b, FileName = file.FileName, FileSize = b.Length, Created = DateTime.Now });
                    }
                }
                catch (Exception ex)
                {
                    return Json(new { Message = "Error in saving file" });
                }
            }
            _advRepository.Save(model);

            return View("Success");
        }


        [HttpPost]
        public void Report(int page, string couse, string text)
        {
            using (var a = new AdvContext())
            {
                a.Database.ExecuteSqlCommand("insert into ReportAbuse (AdvId, couse, text) values ({0}, {1}, {2})", page, couse, text);
            }
        }


        [HttpPost]
        public void SiteMessage(int page, int userId, string phone, string mail, string text)
        {
            using (var a = new AdvContext())
            {
                a.Database.ExecuteSqlCommand("insert into Sitemessage (AdvId,FromId,  FromPhone, FromEmail, Text) values ({0}, {1}, {2}, {3}, {4})", page, userId, phone, mail, text);
            }
        }



        [OutputCache(Location = System.Web.UI.OutputCacheLocation.Any, Duration = 60)]
        public ActionResult AdvDetails([BindParameter("id")] string AdvNo)
        {
            var adv = _advRepository.Get(Convert.ToInt32(AdvNo)) ?? new AdvModel();
            var l = (List<AdvModel>)Session["LastSearch"];

            if (l != null)
            {
                if (l.Any(x => x.Id == adv.Id))
                {
                    adv._next = l.Where(x => x.Id == adv.Id).FirstOrDefault()._next;
                    adv._previous = l.Where(x => x.Id == adv.Id).FirstOrDefault()._previous;
                    if (adv._next > 0)
                        adv.next = _advRepository.Get(adv._next);
                    if (adv._previous > 0)
                        adv.previous = _advRepository.Get(adv._previous);
                }
            }

            if (adv.SubCategory == _carCategory)
            {
                var tmp = _advRepository.GetCar(Convert.ToInt32(AdvNo));

                
                

                if (tmp != null)
                {
                    if (AdvRepository._BrandsPairs.FirstOrDefault(x => x.Id == tmp.Brand) != null && AdvRepository._ModelPairs.FirstOrDefault(x => x.Id == tmp.Model) != null)
                        tmp.strName = (AdvRepository._BrandsPairs.FirstOrDefault(x => x.Id == tmp.Brand).Name) + " " + (AdvRepository._ModelPairs.FirstOrDefault(x => x.Id == tmp.Model).Name);

                    tmp._featuredList = adv._featuredList;
                    tmp._simalarList = adv._simalarList;
                    adv = tmp;
                }
            }



            adv.CurrentUser = _advRepository.GetUser(adv.SellerId.HasValue ? adv.SellerId.Value : 0);
            _advRepository.IncreaseViewCount(Convert.ToInt32(AdvNo), adv.ViewCount);

            //SEO
            List<int> cats = new List<int>();
            cats.Add(19);
            var CatSeoPrefix = cats.Contains(adv.SubCategory) ? "Найти работу " : "Купить ";
            ViewBag.Message = string.Format("{2} {0} в {1}", adv.Name + " " + adv.condition.GetDescription(), adv.LocationName, CatSeoPrefix);
            ViewBag.Keywords = string.Format("{2} {0} в {1}", adv.Name + " " + adv.condition.GetDescription(), adv.LocationName, CatSeoPrefix);
            ViewBag.Description = adv.Description;

            return View(adv);
        }

        public sealed class StringWriterWithEncoding : StringWriter
        {
            private readonly Encoding encoding;

            public StringWriterWithEncoding(Encoding encoding)
            {
                this.encoding = encoding;
            }

            public override Encoding Encoding
            {
                get { return encoding; }
            }
        }


        public void XmlFeed()
        {
            XmlWriterSettings settings = new XmlWriterSettings()
            {
                OmitXmlDeclaration = false,
                Encoding = Encoding.UTF8
            };
            

Controllers/PrivateOfficeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdvSpareAuto.Controllers
{
    public class PrivateOfficeController : Controller
    {
        //
        // GET: /PrivateOffice/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

Views/Home/CarSale.cshtml
@model dynamic

@{
    ViewBag.Title= "title";
}


<div class="main-container">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 login-box">
                <div class="panel panel-default">
                    <div class="panel-intro text-center">
                        <h2>Дать бесплатное объявление о продаже автомобиля</h2>
                    </div>
                    <div class="panel-body">


                        <div style="color: #494949; margin: 20px 0;">
                            <p>
                                Где разместить объявление о продаже автомобиля? На adv.spare-auto.com — одном из
                                крупнейших интернет-порталов в России по продаже автомобилей.
                            </p>

                            <p>
                                Здесь вы всегда найдете тысячи платных и бесплатных объявлений от частных
                                лиц о продаже автомобилей.
                            </p>

                            <p>
                                На adv.spare-auto.com Вы можете бесплатно разместить объявление о продаже
                                легкового автомобиля, подать объявление по продаже легкого коммерческого
                                транспорта, добавить объвление об автобусе, грузовике, прицепе, фургоне или, дать объвление о продаже ретро автомобиля. 
                                adv.spare-auto.com позволяет подавать объявления с фотографиями, полным описанием и без регистрации.
                            </p>

                            <p>
                                На адв спар авто ру дать объявление о продаже автомобиля бесплатно — проще
                                простого!
                            </p>

                            <h2 style="font: normal 22px Arial, sans-serif">Подать объявление без регистрации</h2>

                            <ul class="rare" style="margin: 10px 0 10px 10px;">
                                <li>Вы можете бесплатно дать объявление на adv.spare-auto.com.</li>
                                <li>
                                    Число ваших объявлений одновременно присутствующих на сайте неограничено
                                    
                                </li>
                                <li>Максимально количество фотографий в объявлении — 5.</li>
                                <li>Размер фотографий — до 400Кб.</li>
                                <li>Детальное описание транспортного средства.</li>
                                <li>Подача объявлений без регистрации.</li>
                            </ul>


                            <div class="postadd">
                                @Html.ActionLink("Разместить объявление о продаже авто", "PostCarAdv", "Adv", null, new { @class= "btn btn-border btn-danger" })
                            </div>
                                <br>
                                <br>

                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=1> - Каталог авто Ульяновск</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=10> - Каталог авто Кострома</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=100> - Каталог авто Майкоп</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=103> - Каталог авто Челябинск</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=107> - Каталог авто Астрахань</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=108> - Каталог авто Воронеж</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=109> - Каталог авто Ленинск-Кузнецкий</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=110> - Каталог авто Новосибирск</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=111> - Каталог авто Коломна</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=112> - Каталог авто Благовещенск</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=115> - Каталог авто Тамбов</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=117> - Каталог авто Владимир</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=120> - Каталог авто Альметьевск</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=123> - Каталог авто Ставрополь</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=124> - Каталог авто Курск</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=126> - Каталог авто Бийск</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=131> - Каталог авто Калуга</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=137> - Каталог авто Самара</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=138> - Каталог авто Сыктывкар</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=139> - Каталог авто Томск</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=14> - Каталог авто Октябрьский</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=141> - Каталог авто Санкт-Петербург</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=144> - Каталог авто Ростов-на-Дону</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=149> - Каталог авто Архангельск</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=151> - Каталог авто Улан-Удэ</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=153> - Каталог авто Пенза</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=158> - Каталог авто Краснодар</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=162> - Каталог авто Екатеринбург</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=163> - Каталог авто Смоленск</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=164> - Каталог авто Волжский</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=165> - Каталог авто Ханты-Мансийск</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=173> - Каталог авто Минск</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=18> - Каталог авто Элиста</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=19> - Каталог авто Иркутск</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=2> - Каталог авто Брянск</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=216> - Каталог авто Севастополь</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=217> - Каталог авто Симферополь</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=22> - Каталог авто Москва</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=234> - Каталог авто Белая Церковь</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=241> - Каталог авто Каменец-Подольский</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=243> - Каталог авто Александрия</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=256> - Каталог авто Уральск</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=26> - Каталог авто Ижевск</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=266> - Каталог авто Bath</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=29> - Каталог авто Владивосток</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=36> - Каталог авто Оренбург</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=38> - Каталог авто Белгород</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=40> - Каталог авто Хабаровск</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=42> - Каталог авто Кемерово</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=47> - Каталог авто Казань</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=49> - Каталог авто Волгоград</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=55> - Каталог авто Петрозаводск</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=56> - Каталог авто Омск</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=59> - Каталог авто Чебоксары</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=6> - Каталог авто Тула</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=61> - Каталог авто Киров</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=62> - Каталог авто Пермь</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=72> - Каталог авто Барнаул</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=73> - Каталог авто Калининград</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=80> - Каталог авто Красноярск</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=82> - Каталог авто Вологда</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=85> - Каталог авто Ярославль</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=87> - Каталог авто Саратов</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=89> - Каталог авто Тюмень</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=90> - Каталог авто Тверь</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=92> - Каталог авто Нижний Новгород</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=93> - Каталог авто Нижний Тагил</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=95> - Каталог авто Уфа</a>
                                <a href=http://adv.spare-auto.com/Category/Search?category=49&location=96> - Каталог авто Иваново</a>

                                @* <p>Если вы продаете другой вид ТС, то воспользуйтесь нашими специализированными сервисами.</p>
            <div class="ac">
                <div style="display: inline-block;">
                    <table class="al" style="margin-top: 20px;">
                        <tbody>
                            <tr>
                                <td style="padding: 20px 150px 20px 0;"><a href="http://www.hitruck.ru/direct/"><img src="http://www.hitruck.ru/i/hitruck.ru/logo.png"></a></td>
                                <td style="padding: 20px 0;"><a href="http://www.motorate.ru/direct/"><img src="http://www.motorate.ru/i/motorate.ru/logo.png" data-pin-nopin="true"></a></td>
                            </tr>
                            <tr>
                                <td style="padding: 20px 150px 20px 0;"><a href="http://www.planetwater.ru/direct/"><img src="http://www.planetwater.ru/i/planetwater.ru/logo.png" data-pin-nopin="true"></a></td>
                                <td style="padding: 20px 0;"><a href="http://www.truesky.ru/direct/"><img src="http://www.truesky.ru/i/truesky.ru/logo.png" data-pin-nopin="true"></a></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>*@
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Home/JobSearch.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
}

<div class="inner-box-ads relative">
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- Top advdetails box -->
    <ins class="adsbygoogle"
         style="display:block"
         data-ad-client="ca-pub-9707096941681181"
         data-ad-slot="3372005550"
         data-ad-format="auto"></ins>
    <script>
        (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
</div>



<div class="main-container">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 login-box">
                <div class="panel panel-default">
                    <div class="panel-intro text-center">
                        <h2>Поиск работы</h2>
                    </div>
                    <div class="panel-body">


                        <div class="rua-p-c-light">
                            <h2 class="headline centered mtmb rua-p-c-default">Почему стоит создать резюме на adv.spare-auto.com?</h2>
                            <div class="row">
                                
                                <div class="col-sm-6">
                                    <p>
                                        <span class="col-sm-6">Увеличьте шансы найти работу.</span> Главная причина составить резюме онлайн – вас увидит работодатель! И речь не о вашем фото. По нашим данным, половина работодателей находят нужных специалистов именно в базе резюме еще до размещения своей вакансии.
                                    </p>
                                    <p>
                                        <span class="col-sm-6">Профессионализм.</span> Конструктор резюме adv.spare-auto.ru разработан экспертами в области HR. При составлении резюме система подскажет вам, о чем нужно рассказать. Это поможет работодателю сразу увидеть нужную информацию и узнать о всех ваших сильных сторонах. Кроме того, разместить резюме на сайте можно абсолютно бесплатно.
                                    </p>
                                </div>
                                <div class="col-sm-6">
                                    <p>
                                        <span class="col-sm-3">Доступность.</span> После создания профессионального резюме на adv.spare-auto.ru вам достаточно одного звонка, чтобы связаться с работодателем. Также вы сможете в любой момент скачать свое CV, чтобы распечатать и, например, пойти на собеседование или ярмарку вакансий.
                                    </p>
                                    <p>
                                        <span class="col-sm-3">Актуальность.</span> Подписывайтесь на рассылки вакансий и управляйте настройками, чтобы первыми узнавать о свежих вакансиях от проверенных работодателей. Благодаря гибким фильтрам – на вашу почту будут приходить только те предложения о работе, которые подходят всем вашим требованиям.
                                    </p>
                                </div>
                            </div></div>


                        <div class="postadd">
                            @Html.ActionLink("Разместить резюме", "PostResume", "Adv", null, new { @class = "btn btn-block btn-border btn-post btn-danger" })
                        </div>
                        <a href=http://adv.spare-auto.com/Category/Search?category=19&location=162> - Каталог вакансий Екатеринбург</a>
                        <a href=http://adv.spare-auto.com/Category/Search?category=19&location=74> - Каталог вакансий Ноябрьск</a>
                        @* <p>Если вы продаете другой вид ТС, то воспользуйтесь нашими специализированными сервисами.</p>
                            <div class="ac">
                                <div style="display: inline-block;">
                                    <table class="al" style="margin-top: 20px;">
                                        <tbody>
                                            <tr>
                                                <td style="padding: 20px 150px 20px 0;"><a href="http://www.hitruck.ru/direct/"><img src="http://www.hitruck.ru/i/hitruck.ru/logo.png"></a></td>
                                                <td style="padding: 20px 0;"><a href="http://www.motorate.ru/direct/"><img src="http://www.motorate.ru/i/motorate.ru/logo.png" data-pin-nopin="true"></a></td>
                                            </tr>
                                            <tr>
                                                <td style="padding: 20px 150px 20px 0;"><a href="http://www.planetwater.ru/direct/"><img src="http://www.planetwater.ru/i/planetwater.ru/logo.png" data-pin-nopin="true"></a></td>
                                                <td style="padding: 20px 0;"><a href="http://www.truesky.ru/direct/"><img src="http://www.truesky.ru/i/truesky.ru/logo.png" data-pin-nopin="true"></a></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>*@
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Home/SavedSearch.cshtml
@{
    ViewBag.Title = "SavedSearch";
}

<h2>SavedSearch</h2>

Views/Home/Success.cshtml
@model DAL.Review

<div class="main-container">
    <div class="container">
        <div class="row">
            <div class="col-md-12 page-content">
                <div class="inner-box category-content">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="alert alert-success pgray  alert-lg" role="alert">
                                <h2 class="no-margin no-padding">
                                    &#10004; Ваш аккаунт закрыт. Спасибо, что были с нами. <br />
                                    Ждем вашего возвращения, Вы всегда можете создать новый аккаунт
                                </h2>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.page-content -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container -->
    </div>
</div>